version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: "@testing-library/dom"
    versions:
    - 7.29.4
    - 7.30.0
    - 7.30.1
  - dependency-name: "@testing-library/react-hooks"
    versions:
    - 5.0.0
    - 5.0.3
    - 5.1.0
  - dependency-name: eslint
    versions:
    - 7.18.0
    - 7.22.0
  - dependency-name: "@bbc/psammead-test-helpers"
    versions:
    - 6.0.0
    - 6.0.2
    - 6.0.3
  - dependency-name: "@bbc/psammead-heading-index"
    versions:
    - 3.0.10
    - 3.0.13
  - dependency-name: jest-silent-reporter
    versions:
    - 0.4.0
